owner: alanviotto
repo: status

sites:
  - name: Portal Prod
    url: https://portal.dialab.ai
    
  - name: Portal Staging
    url: https://portal-dialab.webflow.io
    
  - name: API Inteligencia de Vida
    url: https://api.login.inteligenciadevida.tec.br/api/Client
    headers:
      - "accept: */*"
      - "x-app-id: $INTELIGENCIA_VIDA_APP_ID"
      
  - name: Banco Supabase Prod
    url: $SUPABASE_PROD_URL/rest/v1/
    headers:
      - "apikey: $SUPABASE_PROD_KEY"
      - "Authorization: Bearer $SUPABASE_PROD_KEY"
      
  - name: Banco Supabase Staging
    url: $SUPABASE_STG_URL/rest/v1/
    headers:
      - "apikey: $SUPABASE_STG_KEY"
      - "Authorization: Bearer $SUPABASE_STG_KEY"

status-website:
  name: Dialab Status
  introTitle: "Página de Status da Infraestrutura do Portal Dialab."
  introMessage: "Monitoramento em tempo real dos nossos portais, bancos de dados e APIs externas."
